version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: game-postgres
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/game
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=password
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/game
      - SPRING_LIQUIBASE_USER=user
      - SPRING_LIQUIBASE_PASSWORD=password

volumes:
  postgres_data:
